In [1]:
import pandas as pd
df = pd.read_csv('2020_taxi_trips.csv')

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14276\1329109742.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('2020_taxi_trips.csv')

In [2]:
df.columns

Index(['VendorID', 'lpep_pickup_datetime', 'lpep_dropoff_datetime',
       'store_and_fwd_flag', 'RatecodeID', 'PULocationID', 'DOLocationID',
       'passenger_count', 'trip_distance', 'fare_amount', 'extra', 'mta_tax',
       'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount',
       'payment_type', 'trip_type', 'congestion_surcharge'],
      dtype='object')

In [3]:
df.nunique()

VendorID                       2
lpep_pickup_datetime     1366194
lpep_dropoff_datetime    1366295
store_and_fwd_flag             2
RatecodeID                     7
PULocationID                 260
DOLocationID                 260
passenger_count               10
trip_distance               4607
fare_amount                 7890
extra                         74
mta_tax                        5
tip_amount                  2146
tolls_amount                 182
improvement_surcharge          3
total_amount                9598
payment_type                   5
trip_type                      2
congestion_surcharge           5
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1734051 entries, 0 to 1734050
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               float64
 1   lpep_pickup_datetime   object
 2   lpep_dropoff_datetime  object
 3   store_and_fwd_flag     object
 4   RatecodeID             float64
 5   PULocationID           int64
 6   DOLocationID           int64
 7   passenger_count        float64
 8   trip_distance          float64
 9   fare_amount            float64
 10  extra                  float64
 11  mta_tax                float64
 12  tip_amount             float64
 13  tolls_amount           float64
 14  improvement_surcharge  float64
 15  total_amount           float64
 16  payment_type           float64
 17  trip_type              float64
 18  congestion_surcharge   float64
dtypes: float64(14), int64(2), object(3)
memory usage: 251.4+ MB

In [5]:
df.shape

(1734051, 19)

In [6]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2.0,2020-01-01 06:47:28.000,2020-01-01 06:52:54.000,N,1.0,74,75,1.0,1.47,6.50,0.0,0.5,0.0,0.00,0.3,7.3,2.0,1.0,0.0
1,2.0,2020-01-01 13:25:34.000,2020-01-01 13:30:43.000,N,1.0,74,75,1.0,1.49,6.50,0.0,0.5,0.0,0.00,0.3,7.3,2.0,1.0,0.0
2,2.0,2020-01-01 14:20:35.000,2020-01-01 14:26:25.000,N,1.0,74,75,1.0,1.31,6.50,0.0,0.5,0.0,0.00,0.3,7.3,2.0,1.0,0.0
3,2.0,2020-01-02 06:56:47.000,2020-01-02 07:03:03.000,N,1.0,74,75,1.0,1.43,6.50,0.0,0.5,0.0,0.00,0.3,7.3,2.0,1.0,0.0
4,2.0,2020-01-02 09:34:46.000,2020-01-02 09:41:02.000,N,1.0,74,75,1.0,1.10,6.50,0.0,0.5,0.0,0.00,0.3,7.3,2.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1734046,NaN,2020-08-18 02:26:00.000,2020-08-18 02:52:00.000,NaN,NaN,117,76,NaN,10.64,46.61,0.0,0.0,0.0,2.29,0.3,49.2,NaN,NaN,NaN
1734047,NaN,2020-08-18 03:02:00.000,2020-08-18 03:43:00.000,NaN,NaN,117,232,NaN,24.39,93.41,0.0,0.0,0.0,2.29,0.3,96.0,NaN,NaN,NaN
1734048,NaN,2020-08-25 03:16:00.000,2020-08-25 03:54:00.000,NaN,NaN,117,232,NaN,24.65,93.41,0.0,0.0,0.0,2.29,0.3,96.0,NaN,NaN,NaN
1734049,NaN,2020-08-30 02:48:00.000,2020-08-30 03:40:00.000,NaN,NaN,117,232,NaN,20.26,93.41,0.0,0.0,0.0,2.29,0.3,96.0,NaN,NaN,NaN
1734050,NaN,2020-08-04 04:37:00.000,2020-08-04 05:11:00.000,NaN,NaN,117,138,NaN,19.32,65.51,0.0,0.0,0.0,2.29,0.3,68.1,NaN,NaN,NaN

# DROPPING IRRELEVANT COLUMNS

In [7]:
df.drop(columns=['payment_type','passenger_count','trip_type','congestion_surcharge','VendorID','store_and_fwd_flag','RatecodeID','fare_amount','extra','mta_tax','tip_amount','tolls_amount','improvement_surcharge'],inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1734051 entries, 0 to 1734050
Data columns (total 6 columns):
 #   Column                 Dtype
---  ------                 -----
 0   lpep_pickup_datetime   object
 1   lpep_dropoff_datetime  object
 2   PULocationID           int64
 3   DOLocationID           int64
 4   trip_distance          float64
 5   total_amount           float64
dtypes: float64(2), int64(2), object(2)
memory usage: 79.4+ MB

# REPLACING COLUMNS WITH KEY VALUES

In [9]:
df['lpep_pickup_datetime'] = pd.to_datetime(df['lpep_pickup_datetime'])
df['lpep_dropoff_datetime'] = pd.to_datetime(df['lpep_dropoff_datetime'])

In [10]:
print(min(df['total_amount']))
print(max(df['total_amount']))

k=[i for i in df['total_amount'] if i < 0]
len(k)

df = df[df['total_amount'] >= 0]

-210.3
803.8

In [11]:
# checking neg values in data
k=[i for i in df['total_amount'] if i < 0]
len(k)

0

In [12]:
df["day"] = df["lpep_pickup_datetime"].dt.day
df["month"] = df["lpep_pickup_datetime"].dt.month
df['hour'] = df['lpep_pickup_datetime'].dt.hour

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14276\349951313.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["day"] = df["lpep_pickup_datetime"].dt.day
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14276\349951313.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["month"] = df["lpep_pickup_datetime"].dt.month
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14276\349951313.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hour'] = df['lpep_pickup_datetime'].dt.hour

In [13]:
df.head(2)

,lpep_pickup_datetime,lpep_dropoff_datetime,PULocationID,DOLocationID,trip_distance,total_amount,day,month,hour
0,2020-01-01 06:47:28,2020-01-01 06:52:54,74,75,1.47,7.3,1,1,6
1,2020-01-01 13:25:34,2020-01-01 13:30:43,74,75,1.49,7.3,1,1,13

In [14]:
df=df[['hour','month','day','PULocationID','DOLocationID','trip_distance','total_amount']]

In [15]:
df = df[~df['PULocationID'].isin([264, 265]) & ~df['DOLocationID'].isin([264, 265])]

#  ONE-HOT ENCODING

In [16]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()

df_ohe = pd.get_dummies(df, columns=['PULocationID', 'DOLocationID'], drop_first=False)
df_ohe

,hour,month,day,trip_distance,total_amount,PULocationID_1,PULocationID_2,PULocationID_3,PULocationID_4,PULocationID_5,...,DOLocationID_254,DOLocationID_255,DOLocationID_256,DOLocationID_257,DOLocationID_258,DOLocationID_259,DOLocationID_260,DOLocationID_261,DOLocationID_262,DOLocationID_263
0,6,1,1,1.47,7.3,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,13,1,1,1.49,7.3,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,14,1,1,1.31,7.3,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,6,1,2,1.43,7.3,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,9,1,2,1.10,7.3,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1734046,2,8,18,10.64,49.2,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1734047,3,8,18,24.39,96.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1734048,3,8,25,24.65,96.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1734049,2,8,30,20.26,96.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1734050,4,8,4,19.32,68.1,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [17]:
df_ohe.dropna(inplace=True)

In [23]:
df_ohe.to_csv('2020_ohe_predix.csv')

# TRAIN-TEST SPLIT

In [18]:
y=df_ohe['total_amount']
x=df_ohe.drop(columns=['total_amount'])

In [19]:
from sklearn.model_selection import  train_test_split
x_train, x_test, y_train , y_test = train_test_split(x,y,random_state=7)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1286391, 520)
(1286391,)
(428797, 520)
(428797,)

# APPLY XGBOOST

In [20]:
import xgboost
xg = xgboost.XGBRegressor()
model = xg.fit(x_train, y_train, verbose=2)

y_pred = model.predict(x_test)
y_pred

array([12.600774, 15.416197,  9.064239, ..., 10.480007, 12.986924,
       21.85103 ], dtype=float32)

# MODEL METRICS

In [21]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error, mean_absolute_percentage_error

mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

rmse = root_mean_squared_error(y_test, y_pred)
print("Root Mean Squared Error:", rmse)

r2 = r2_score(y_test, y_pred)
print("R-squared:", r2)

Mean Absolute Error: 3.6268298692988843
Mean Squared Error: 38.07545375748697
Root Mean Squared Error: 6.170531075805953
R-squared: 0.827104324479164

In [ ]:
# import pickle
# filename = '2020_ohe_xgboost.pkl'
# pickle.dump(model, open(filename, 'wb'))

# LOAD MODEL

In [ ]:
# import pickle 
# model = pickle.load(open('2020_xgboost.pkl','rb'))

In [ ]:
# model

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [ ]:
# model.predict([[1,1,1,41,41,1.4]])

array([9.213638], dtype=float32)